resources:
- repo: self
queue:
  name: Hosted VS2017
  demands: npm

steps:
- task: Npm@1
  displayName: verify
  inputs:
    command: custom

    verbose: false

    customCommand: 'cache verify'

  enabled: false

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: web
    verbose: false


- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: custom
    workingDir: web
    verbose: false
    customCommand: 'run build'

- task: AzureWebApp@1
  displayName: 'Azure Web App Deploy'
  inputs:
    azureSubscription: AzureDevopsplus
    appType: webApp
    appName: AzureWebDevopsplus
    package: '$(System.DefaultWorkingDirectory)/**/web/dist'

