resources:
- repo: self
queue:
  name: Hosted VS2017
  demands: npm

steps:
- task: Npm@1
  displayName: verify
  inputs:
    command: custom

    verbose: false

    customCommand: 'cache verify'

  enabled: false

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: web
    verbose: false


- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: custom
    workingDir: web
    verbose: false
    customCommand: 'run build'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: api/dow.devopsplus.sln
    vstsFeed: '534da1e6-36f5-4fb0-baf6-faee4b20096c'

- task: MSBuild@1
  displayName: 'Build Webapi'
  inputs:
    solution: api/dow.devopsplus.sln
    msbuildArchitecture: x64
    platform: 'any cpu'
    configuration: 'release'
    msbuildArguments: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"'

- task: AzureWebApp@1
  displayName: 'Azure Web Deploy'
  inputs:
    azureSubscription: AzureDevopsplus
    appType: webApp
    appName: AzureWebDevopsplus
    package: '$(System.DefaultWorkingDirectory)/**/web/dist'

- task: AzureRmWebAppDeployment@4
  displayName: 'Azure API Deploy'
  inputs:
    azureSubscription: AzureDevopsplus
    WebAppName: AzureApiDevopsplus
    packageForLinux: '$(build.artifactstagingdirectory)/**/*.zip'
