resources:
- repo: self
queue:
  name: Hosted VS2017
  demands: npm

steps:
- task: Npm@1
  displayName: verify
  inputs:
    command: custom

    verbose: false

    customCommand: 'cache verify'

  enabled: false

- task: Npm@1
  displayName: 'npm install'
  inputs:
    workingDir: web
    verbose: false


- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: custom
    workingDir: web
    verbose: false
    customCommand: 'run build'


- task: AzureRmWebAppDeployment@3
  displayName: 'Azure App Service Deploy: dowtest78789'
  inputs:
    azureSubscription: AzureDevopsplus

    appType: webApp

    WebAppName: dowtest78789

    Package: dist

