resources:
- repo: self
queue:
  name: Hosted VS2017
  demands: npm 

steps:
- task: Npm@1
  displayName: verify
  inputs:
    command: custom

    verbose: false

    customCommand: 'cache verify'

  enabled: false

- task: Npm@1
  displayName: 'npm install'
  inputs:
    verbose: false


- task: Npm@1
  displayName: 'npm custom'
  inputs:
    command: custom

    verbose: false

    customCommand: 'run-script build'


- task: AzureRmWebAppDeployment@3
  displayName: 'Azure App Service Deploy: dowtestabcd237'
  inputs:
    azureSubscription: test2

    appType: webApp

    WebAppName: dowtestabcd237

    Package: dist

